eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: eurekaserver

server:
  port: 9002 #default 8761
    
#eureka.instance.hostname = localhost
#eureka.client.service-url.defaultZone= http://${eureka.instance.hostname}:${server.port}/eureka/
